// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace SmokeQuit.SoapApiServices.DuongLNT.SoapModels;

[DataContract]
public partial class AchievementNhuNq
{
	[DataMember]
	public int AchievementNhuNqid { get; set; }

	[DataMember]
	public string AchievementName { get; set; }

	[DataMember]
	public string Description { get; set; }

	[DataMember]
	public string CriteriaType { get; set; }

	[DataMember]
	public double CriteriaValue { get; set; }

	[DataMember]
	public DateTime? CreatedAt { get; set; }

	[DataMember]
	public virtual ICollection<UserAchievementNhuNq> UserAchievementNhuNqs { get; set; } = new List<UserAchievementNhuNq>();
}