// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace SmokeQuit.SoapApiServices.DuongLNT.SoapModels;

[DataContract]
public partial class BlogPostsAnVt
{
	[DataMember]
	public int BlogPostsAnVtid { get; set; }

	[DataMember]
	public int UserId { get; set; }

	[DataMember]
	public int? PlanId { get; set; }

	[DataMember]
	public string Title { get; set; }

	[DataMember]
	public string Content { get; set; }

	[DataMember]
	public string Category { get; set; }

	[DataMember]
	public string Tags { get; set; }

	[DataMember]
	public bool IsPublic { get; set; }

	[DataMember]
	public int? ViewsCount { get; set; }

	[DataMember]
	public int? LikesCount { get; set; }

	[DataMember]
	public int? CommentsCount { get; set; }

	[DataMember]
	public DateTime? CreatedAt { get; set; }

	[DataMember]
	public DateTime? UpdatedAt { get; set; }

	[DataMember]
	public virtual QuitPlansAnhDtn Plan { get; set; }

	[DataMember]
	public virtual SystemUserAccount User { get; set; }
}