// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SmokeQuit.SoapApiServices.DuongLNT.SoapModels;

[DataContract]
public partial class ChatsLocDpx
{
	[DataMember]
	public int ChatsLocDpxid { get; set; }

	[DataMember]
	public int UserId { get; set; }

	[DataMember]
	public int CoachId { get; set; }

	[DataMember]
	public string Message { get; set; }

	[DataMember]
	public string SentBy { get; set; }

	[DataMember]
	public string MessageType { get; set; }

	[DataMember]
	public bool IsRead { get; set; }

	[DataMember]
	public string AttachmentUrl { get; set; }

	[DataMember]
	public DateTime? ResponseTime { get; set; }

	[DataMember]
	public DateTime? CreatedAt { get; set; }

	[DataMember]
	public virtual CoachesLocDpx Coach { get; set; }

	[DataMember]
	public virtual SystemUserAccount User { get; set; }
}