// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SmokeQuit.SoapApiServices.DuongLNT.SoapModels;

[DataContract]
public partial class CoachesLocDpx
{
	[DataMember]
	public int CoachesLocDpxid { get; set; }

	[DataMember]
	public string FullName { get; set; }

	[DataMember]
	public string Email { get; set; }

	[DataMember]
	public string PhoneNumber { get; set; }

	[DataMember]
	public string Bio { get; set; }

	[DataMember]
	public DateTime? CreatedAt { get; set; }

	[DataMember]
	public virtual ICollection<ChatsLocDpx> ChatsLocDpxes { get; set; } = new List<ChatsLocDpx>();
}