// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace SmokeQuit.SoapApiServices.DuongLNT.SoapModels;

[DataContract]
public partial class LeaderboardsDuongLnt
{
	[DataMember]
	public int? LeaderboardsDuongLntid { get; set; }

	[DataMember]
	[Required(ErrorMessage = "User is required.")]
	public int UserId { get; set; }

	[DataMember]
	public int? PlanId { get; set; }

	[DataMember]
	[Range(0, int.MaxValue, ErrorMessage = "Days smoke-free cannot be negative.")]
	[Required(ErrorMessage = "DaySmokeFree is required.")]
	public int? DaySmokeFree { get; set; }

	[DataMember]
	[Range(0, double.MaxValue, ErrorMessage = "Saved money cannot be negative")]
	[Required(ErrorMessage = "MoneySave is required.")]
	public double? MoneySave { get; set; }

	[DataMember]
	[Range(1, int.MaxValue, ErrorMessage = "Rank position must be greater than 1.")]
	[Required(ErrorMessage = "RankPosition is required.")]
	public int? RankPosition { get; set; }

	[DataMember]
	[Range(0, int.MaxValue, ErrorMessage = "Total achievements cannot be negative")]
	[Required(ErrorMessage = "TotalAchievements is required.")]
	public int? TotalAchievements { get; set; }

	[DataMember]
	[Range(0, double.MaxValue, ErrorMessage = "Progress score cannot be negative")]
	public double? ProgressScore { get; set; }

	[DataMember]
	[StringLength(255, ErrorMessage = "Note must not exceed 255 characters.")]
	[Required(ErrorMessage = "Note is required.")]
	public string Note { get; set; }

	[DataMember]
	[Range(0, int.MaxValue, ErrorMessage = "Streak count cannot be negative.")]
	public int? StreakCount { get; set; }

	[DataMember]
	public int? CommunityContribution { get; set; }

	[DataMember]
	public bool IsTopRanked { get; set; }

	[DataMember]
	public DateTime? LastUpdate { get; set; }

	[DataMember]
	public DateTime? CreatedTime { get; set; }

	public virtual QuitPlansAnhDtn Plan { get; set; }

	public virtual SystemUserAccount User { get; set; }
}