// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace SmokeQuit.SoapApiServices.DuongLNT.SoapModels;

[DataContract]
public partial class LeaderboardsDuongLnt
{
	[DataMember]
	public int? LeaderboardsDuongLntid { get; set; }

	[DataMember]
	[Required(ErrorMessage = "User Id không được để trống.")]
	public int UserId { get; set; }

	[DataMember]
	public int? PlanId { get; set; }

	[DataMember]
	[Range(0, int.MaxValue, ErrorMessage = "Ngày không hút thuốc không được âm")]
	public int? DaySmokeFree { get; set; }

	[DataMember]
	[Range(0, double.MaxValue, ErrorMessage = "Tiền lưu trữ không được âm")]
	public double? MoneySave { get; set; }

	[DataMember]
	[Range(1, int.MaxValue, ErrorMessage = "Xếp hạng vị trí phải lớn hơn 1")]
	public int? RankPosition { get; set; }

	[DataMember]
	[Range(0, int.MaxValue, ErrorMessage = "Tổng số thành tích không được âm")]
	public int? TotalAchievements { get; set; }

	[DataMember]
	[Range(0, double.MaxValue, ErrorMessage = "Điểm tiến bộ không được âm")]
	public double? ProgressScore { get; set; }

	[DataMember]
	[StringLength(255, ErrorMessage = "Ghi chú không được vượt quá 255 ký tự.")]
    public string Note { get; set; }

	[DataMember]
	[Range(0, int.MaxValue, ErrorMessage = "Chuỗi đếm không được âm.")]
	public int? StreakCount { get; set; }

	[DataMember]
	[Range(0, int.MaxValue, ErrorMessage = "Đóng góp của cộng đồng không được âm.")]
	public int? CommunityContribution { get; set; }

	[DataMember]
	public bool IsTopRanked { get; set; }

	[DataMember]
	public DateTime? LastUpdate { get; set; }

	[DataMember]
	public DateTime? CreatedTime { get; set; }

	[DataMember]
	public virtual QuitPlansAnhDtn Plan { get; set; }

	[DataMember]
	public virtual SystemUserAccount User { get; set; }
}