// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SmokeQuit.SoapApiServices.DuongLNT.SoapModels;

[DataContract]
public partial class MembershipPlansAnhDtn
{
	[DataMember]
	public int MembershipPlansAnhDtnid { get; set; }

	[DataMember]
	public string PlanName { get; set; }

	[DataMember]
	public string Description { get; set; }

	[DataMember]
	public double Price { get; set; }

	[DataMember]
	public int DurationDays { get; set; }

	[DataMember]
	public DateTime? CreatedAt { get; set; }

	[DataMember]
	public virtual ICollection<QuitPlansAnhDtn> QuitPlansAnhDtns { get; set; } = new List<QuitPlansAnhDtn>();
}