// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SmokeQuit.SoapApiServices.DuongLNT.SoapModels;

[DataContract]
public partial class ProgressRecordsHoangPx
{
	[DataMember]
	public int ProgressRecordsHoangPxid { get; set; }

	[DataMember]
	public int UserId { get; set; }

	[DataMember]
	public int? SupportMethodId { get; set; }

	[DataMember]
	public int? CigarettesSmoked { get; set; }

	[DataMember]
	public string HealthStatus { get; set; }

	[DataMember]
	public double? MoneySaved { get; set; }

	[DataMember]
	public int? DaysSmokeFree { get; set; }

	[DataMember]
	public DateTime RecordedAt { get; set; }

	[DataMember]
	public string Mood { get; set; }

	[DataMember]
	public bool HadCraving { get; set; }

	[DataMember]
	public int? CravingLevel { get; set; }

	[DataMember]
	public string Notes { get; set; }

	[DataMember]
	public DateTime? ModifiedAt { get; set; }

	[DataMember]
	public virtual SupportMethodsHoangPx SupportMethod { get; set; }

	[DataMember]
	public virtual SystemUserAccount User { get; set; }
}