// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SmokeQuit.SoapApiServices.DuongLNT.SoapModels;

[DataContract]
public partial class QuitPlansAnhDtn
{
	[DataMember]
	public int? QuitPlansAnhDtnid { get; set; }

	[DataMember]
	public int UserId { get; set; }

	[DataMember]
	public int? MembershipPlanId { get; set; }

	[DataMember]
	public string Reason { get; set; }

	[DataMember]
	public DateTime StartDate { get; set; }

	[DataMember]
	public DateTime? ExpectedQuitDate { get; set; }

	[DataMember]
	public int? DailyCigaretteTarget { get; set; }

	[DataMember]
	public int? WeeklyCheckinFrequency { get; set; }

	[DataMember]
	public string MotivationalMessage { get; set; }

	[DataMember]
	public string HealthGoals { get; set; }

	[DataMember]
	public double? BudgetSavingGoal { get; set; }

	[DataMember]
	public bool ReceiveMotivationReminder { get; set; }

	[DataMember]
	public bool IsCustomizedPlan { get; set; }

	[DataMember]
	public DateTime? CreatedAt { get; set; }

	[DataMember]
	public DateTime? UpdatedAt { get; set; }

	[DataMember]
	public virtual ICollection<BlogPostsAnVt> BlogPostsAnVts { get; set; } = new List<BlogPostsAnVt>();

	[DataMember]
	public virtual ICollection<LeaderboardsDuongLnt> LeaderboardsDuongLnts { get; set; } = new List<LeaderboardsDuongLnt>();

	[DataMember]
	public virtual MembershipPlansAnhDtn MembershipPlan { get; set; }

	[DataMember]
	public virtual SystemUserAccount User { get; set; }
}