// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace SmokeQuit.SoapApiServices.DuongLNT.SoapModels;

[DataContract]
public partial class SupportMethodsHoangPx
{
	[DataMember]
	public int SupportMethodsHoangPxid { get; set; }

	[DataMember]
	public string MethodName { get; set; }

	[DataMember]
	public string Description { get; set; }

	[DataMember]
	public virtual ICollection<ProgressRecordsHoangPx> ProgressRecordsHoangPxes { get; set; } = new List<ProgressRecordsHoangPx>();
}