// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace SmokeQuit.SoapApiServices.DuongLNT.SoapModels;

[DataContract]
public partial class UserAchievementNhuNq
{
	[DataMember]
	public int UserAchievementNhuNqid { get; set; }

	[DataMember]
	public int UserId { get; set; }

	[DataMember]
	public int AchievementId { get; set; }

	[DataMember]
	public DateTime AchievedAt { get; set; }

	[DataMember]
	public bool Shared { get; set; }

	[DataMember]
	public bool NotificationSent { get; set; }

	[DataMember]
	public int? RewardPoints { get; set; }

	[DataMember]
	public int? CommentCount { get; set; }

	[DataMember]
	public int? LikeCount { get; set; }

	[DataMember]
	public DateTime? CreatedAt { get; set; }

	[DataMember]
	public virtual AchievementNhuNq Achievement { get; set; }

	[DataMember]
	public virtual SystemUserAccount User { get; set; }
}