//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaderboardsDuongLntWCFServiceRef
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeaderboardsDuongLnt", Namespace="http://schemas.datacontract.org/2004/07/SmokeQuit.SoapApiService.DuongLNT.SoapMod" +
        "els")]
    public partial class LeaderboardsDuongLnt : object
    {
        
        private LeaderboardsDuongLntWCFServiceRef.QuitPlansAnhDtn PlanField;
        
        private LeaderboardsDuongLntWCFServiceRef.SystemUserAccount UserField;
        
        private System.Nullable<int> LeaderboardsDuongLntidField;
        
        private int UserIdField;
        
        private System.Nullable<int> PlanIdField;
        
        private System.Nullable<int> DaySmokeFreeField;
        
        private System.Nullable<double> MoneySaveField;
        
        private System.Nullable<int> RankPositionField;
        
        private System.Nullable<int> TotalAchievementsField;
        
        private System.Nullable<double> ProgressScoreField;
        
        private string NoteField;
        
        private System.Nullable<int> StreakCountField;
        
        private System.Nullable<int> CommunityContributionField;
        
        private bool IsTopRankedField;
        
        private System.Nullable<System.DateTime> LastUpdateField;
        
        private System.Nullable<System.DateTime> CreatedTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.QuitPlansAnhDtn Plan
        {
            get
            {
                return this.PlanField;
            }
            set
            {
                this.PlanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.SystemUserAccount User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> LeaderboardsDuongLntid
        {
            get
            {
                return this.LeaderboardsDuongLntidField;
            }
            set
            {
                this.LeaderboardsDuongLntidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> DaySmokeFree
        {
            get
            {
                return this.DaySmokeFreeField;
            }
            set
            {
                this.DaySmokeFreeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<double> MoneySave
        {
            get
            {
                return this.MoneySaveField;
            }
            set
            {
                this.MoneySaveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<int> RankPosition
        {
            get
            {
                return this.RankPositionField;
            }
            set
            {
                this.RankPositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<int> TotalAchievements
        {
            get
            {
                return this.TotalAchievementsField;
            }
            set
            {
                this.TotalAchievementsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<double> ProgressScore
        {
            get
            {
                return this.ProgressScoreField;
            }
            set
            {
                this.ProgressScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<int> StreakCount
        {
            get
            {
                return this.StreakCountField;
            }
            set
            {
                this.StreakCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<int> CommunityContribution
        {
            get
            {
                return this.CommunityContributionField;
            }
            set
            {
                this.CommunityContributionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool IsTopRanked
        {
            get
            {
                return this.IsTopRankedField;
            }
            set
            {
                this.IsTopRankedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public System.Nullable<System.DateTime> LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public System.Nullable<System.DateTime> CreatedTime
        {
            get
            {
                return this.CreatedTimeField;
            }
            set
            {
                this.CreatedTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuitPlansAnhDtn", Namespace="http://schemas.datacontract.org/2004/07/SmokeQuit.SoapApiServices.DuongLNT.SoapMo" +
        "dels")]
    public partial class QuitPlansAnhDtn : object
    {
        
        private LeaderboardsDuongLntWCFServiceRef.BlogPostsAnVt[] BlogPostsAnVtsField;
        
        private System.Nullable<double> BudgetSavingGoalField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private System.Nullable<int> DailyCigaretteTargetField;
        
        private System.Nullable<System.DateTime> ExpectedQuitDateField;
        
        private string HealthGoalsField;
        
        private bool IsCustomizedPlanField;
        
        private LeaderboardsDuongLntWCFServiceRef.LeaderboardsDuongLnt[] LeaderboardsDuongLntsField;
        
        private LeaderboardsDuongLntWCFServiceRef.MembershipPlansAnhDtn MembershipPlanField;
        
        private System.Nullable<int> MembershipPlanIdField;
        
        private string MotivationalMessageField;
        
        private System.Nullable<int> QuitPlansAnhDtnidField;
        
        private string ReasonField;
        
        private bool ReceiveMotivationReminderField;
        
        private System.DateTime StartDateField;
        
        private System.Nullable<System.DateTime> UpdatedAtField;
        
        private LeaderboardsDuongLntWCFServiceRef.SystemUserAccount UserField;
        
        private int UserIdField;
        
        private System.Nullable<int> WeeklyCheckinFrequencyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.BlogPostsAnVt[] BlogPostsAnVts
        {
            get
            {
                return this.BlogPostsAnVtsField;
            }
            set
            {
                this.BlogPostsAnVtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> BudgetSavingGoal
        {
            get
            {
                return this.BudgetSavingGoalField;
            }
            set
            {
                this.BudgetSavingGoalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DailyCigaretteTarget
        {
            get
            {
                return this.DailyCigaretteTargetField;
            }
            set
            {
                this.DailyCigaretteTargetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpectedQuitDate
        {
            get
            {
                return this.ExpectedQuitDateField;
            }
            set
            {
                this.ExpectedQuitDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HealthGoals
        {
            get
            {
                return this.HealthGoalsField;
            }
            set
            {
                this.HealthGoalsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCustomizedPlan
        {
            get
            {
                return this.IsCustomizedPlanField;
            }
            set
            {
                this.IsCustomizedPlanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.LeaderboardsDuongLnt[] LeaderboardsDuongLnts
        {
            get
            {
                return this.LeaderboardsDuongLntsField;
            }
            set
            {
                this.LeaderboardsDuongLntsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.MembershipPlansAnhDtn MembershipPlan
        {
            get
            {
                return this.MembershipPlanField;
            }
            set
            {
                this.MembershipPlanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MembershipPlanId
        {
            get
            {
                return this.MembershipPlanIdField;
            }
            set
            {
                this.MembershipPlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivationalMessage
        {
            get
            {
                return this.MotivationalMessageField;
            }
            set
            {
                this.MotivationalMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QuitPlansAnhDtnid
        {
            get
            {
                return this.QuitPlansAnhDtnidField;
            }
            set
            {
                this.QuitPlansAnhDtnidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReceiveMotivationReminder
        {
            get
            {
                return this.ReceiveMotivationReminderField;
            }
            set
            {
                this.ReceiveMotivationReminderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.SystemUserAccount User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WeeklyCheckinFrequency
        {
            get
            {
                return this.WeeklyCheckinFrequencyField;
            }
            set
            {
                this.WeeklyCheckinFrequencyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUserAccount", Namespace="http://schemas.datacontract.org/2004/07/SmokeQuit.SoapApiServices.DuongLNT.SoapMo" +
        "dels")]
    public partial class SystemUserAccount : object
    {
        
        private string ApplicationCodeField;
        
        private LeaderboardsDuongLntWCFServiceRef.BlogPostsAnVt[] BlogPostsAnVtsField;
        
        private LeaderboardsDuongLntWCFServiceRef.ChatsLocDpx[] ChatsLocDpxesField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        private string EmailField;
        
        private string EmployeeCodeField;
        
        private string FullNameField;
        
        private bool IsActiveField;
        
        private LeaderboardsDuongLntWCFServiceRef.LeaderboardsDuongLnt[] LeaderboardsDuongLntsField;
        
        private string ModifiedByField;
        
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        private string PasswordField;
        
        private string PhoneField;
        
        private LeaderboardsDuongLntWCFServiceRef.ProgressRecordsHoangPx[] ProgressRecordsHoangPxesField;
        
        private LeaderboardsDuongLntWCFServiceRef.QuitPlansAnhDtn[] QuitPlansAnhDtnsField;
        
        private string RequestCodeField;
        
        private int RoleIdField;
        
        private int UserAccountIdField;
        
        private LeaderboardsDuongLntWCFServiceRef.UserAchievementNhuNq[] UserAchievementNhuNqsField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationCode
        {
            get
            {
                return this.ApplicationCodeField;
            }
            set
            {
                this.ApplicationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.BlogPostsAnVt[] BlogPostsAnVts
        {
            get
            {
                return this.BlogPostsAnVtsField;
            }
            set
            {
                this.BlogPostsAnVtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.ChatsLocDpx[] ChatsLocDpxes
        {
            get
            {
                return this.ChatsLocDpxesField;
            }
            set
            {
                this.ChatsLocDpxesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeCode
        {
            get
            {
                return this.EmployeeCodeField;
            }
            set
            {
                this.EmployeeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.LeaderboardsDuongLnt[] LeaderboardsDuongLnts
        {
            get
            {
                return this.LeaderboardsDuongLntsField;
            }
            set
            {
                this.LeaderboardsDuongLntsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.ProgressRecordsHoangPx[] ProgressRecordsHoangPxes
        {
            get
            {
                return this.ProgressRecordsHoangPxesField;
            }
            set
            {
                this.ProgressRecordsHoangPxesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.QuitPlansAnhDtn[] QuitPlansAnhDtns
        {
            get
            {
                return this.QuitPlansAnhDtnsField;
            }
            set
            {
                this.QuitPlansAnhDtnsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestCode
        {
            get
            {
                return this.RequestCodeField;
            }
            set
            {
                this.RequestCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserAccountId
        {
            get
            {
                return this.UserAccountIdField;
            }
            set
            {
                this.UserAccountIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.UserAchievementNhuNq[] UserAchievementNhuNqs
        {
            get
            {
                return this.UserAchievementNhuNqsField;
            }
            set
            {
                this.UserAchievementNhuNqsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MembershipPlansAnhDtn", Namespace="http://schemas.datacontract.org/2004/07/SmokeQuit.SoapApiServices.DuongLNT.SoapMo" +
        "dels")]
    public partial class MembershipPlansAnhDtn : object
    {
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private string DescriptionField;
        
        private int DurationDaysField;
        
        private int MembershipPlansAnhDtnidField;
        
        private string PlanNameField;
        
        private double PriceField;
        
        private LeaderboardsDuongLntWCFServiceRef.QuitPlansAnhDtn[] QuitPlansAnhDtnsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DurationDays
        {
            get
            {
                return this.DurationDaysField;
            }
            set
            {
                this.DurationDaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MembershipPlansAnhDtnid
        {
            get
            {
                return this.MembershipPlansAnhDtnidField;
            }
            set
            {
                this.MembershipPlansAnhDtnidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanName
        {
            get
            {
                return this.PlanNameField;
            }
            set
            {
                this.PlanNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.QuitPlansAnhDtn[] QuitPlansAnhDtns
        {
            get
            {
                return this.QuitPlansAnhDtnsField;
            }
            set
            {
                this.QuitPlansAnhDtnsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlogPostsAnVt", Namespace="http://schemas.datacontract.org/2004/07/SmokeQuit.SoapApiServices.DuongLNT.SoapMo" +
        "dels")]
    public partial class BlogPostsAnVt : object
    {
        
        private int BlogPostsAnVtidField;
        
        private string CategoryField;
        
        private System.Nullable<int> CommentsCountField;
        
        private string ContentField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private bool IsPublicField;
        
        private System.Nullable<int> LikesCountField;
        
        private LeaderboardsDuongLntWCFServiceRef.QuitPlansAnhDtn PlanField;
        
        private System.Nullable<int> PlanIdField;
        
        private string TagsField;
        
        private string TitleField;
        
        private System.Nullable<System.DateTime> UpdatedAtField;
        
        private LeaderboardsDuongLntWCFServiceRef.SystemUserAccount UserField;
        
        private int UserIdField;
        
        private System.Nullable<int> ViewsCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlogPostsAnVtid
        {
            get
            {
                return this.BlogPostsAnVtidField;
            }
            set
            {
                this.BlogPostsAnVtidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CommentsCount
        {
            get
            {
                return this.CommentsCountField;
            }
            set
            {
                this.CommentsCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublic
        {
            get
            {
                return this.IsPublicField;
            }
            set
            {
                this.IsPublicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LikesCount
        {
            get
            {
                return this.LikesCountField;
            }
            set
            {
                this.LikesCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.QuitPlansAnhDtn Plan
        {
            get
            {
                return this.PlanField;
            }
            set
            {
                this.PlanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.SystemUserAccount User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ViewsCount
        {
            get
            {
                return this.ViewsCountField;
            }
            set
            {
                this.ViewsCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatsLocDpx", Namespace="http://schemas.datacontract.org/2004/07/SmokeQuit.SoapApiServices.DuongLNT.SoapMo" +
        "dels")]
    public partial class ChatsLocDpx : object
    {
        
        private string AttachmentUrlField;
        
        private int ChatsLocDpxidField;
        
        private LeaderboardsDuongLntWCFServiceRef.CoachesLocDpx CoachField;
        
        private int CoachIdField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private bool IsReadField;
        
        private string MessageField;
        
        private string MessageTypeField;
        
        private System.Nullable<System.DateTime> ResponseTimeField;
        
        private string SentByField;
        
        private LeaderboardsDuongLntWCFServiceRef.SystemUserAccount UserField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachmentUrl
        {
            get
            {
                return this.AttachmentUrlField;
            }
            set
            {
                this.AttachmentUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChatsLocDpxid
        {
            get
            {
                return this.ChatsLocDpxidField;
            }
            set
            {
                this.ChatsLocDpxidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.CoachesLocDpx Coach
        {
            get
            {
                return this.CoachField;
            }
            set
            {
                this.CoachField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoachId
        {
            get
            {
                return this.CoachIdField;
            }
            set
            {
                this.CoachIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRead
        {
            get
            {
                return this.IsReadField;
            }
            set
            {
                this.IsReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageType
        {
            get
            {
                return this.MessageTypeField;
            }
            set
            {
                this.MessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ResponseTime
        {
            get
            {
                return this.ResponseTimeField;
            }
            set
            {
                this.ResponseTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SentBy
        {
            get
            {
                return this.SentByField;
            }
            set
            {
                this.SentByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.SystemUserAccount User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgressRecordsHoangPx", Namespace="http://schemas.datacontract.org/2004/07/SmokeQuit.SoapApiServices.DuongLNT.SoapMo" +
        "dels")]
    public partial class ProgressRecordsHoangPx : object
    {
        
        private System.Nullable<int> CigarettesSmokedField;
        
        private System.Nullable<int> CravingLevelField;
        
        private System.Nullable<int> DaysSmokeFreeField;
        
        private bool HadCravingField;
        
        private string HealthStatusField;
        
        private System.Nullable<System.DateTime> ModifiedAtField;
        
        private System.Nullable<double> MoneySavedField;
        
        private string MoodField;
        
        private string NotesField;
        
        private int ProgressRecordsHoangPxidField;
        
        private System.DateTime RecordedAtField;
        
        private LeaderboardsDuongLntWCFServiceRef.SupportMethodsHoangPx SupportMethodField;
        
        private System.Nullable<int> SupportMethodIdField;
        
        private LeaderboardsDuongLntWCFServiceRef.SystemUserAccount UserField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CigarettesSmoked
        {
            get
            {
                return this.CigarettesSmokedField;
            }
            set
            {
                this.CigarettesSmokedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CravingLevel
        {
            get
            {
                return this.CravingLevelField;
            }
            set
            {
                this.CravingLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DaysSmokeFree
        {
            get
            {
                return this.DaysSmokeFreeField;
            }
            set
            {
                this.DaysSmokeFreeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HadCraving
        {
            get
            {
                return this.HadCravingField;
            }
            set
            {
                this.HadCravingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HealthStatus
        {
            get
            {
                return this.HealthStatusField;
            }
            set
            {
                this.HealthStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedAt
        {
            get
            {
                return this.ModifiedAtField;
            }
            set
            {
                this.ModifiedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MoneySaved
        {
            get
            {
                return this.MoneySavedField;
            }
            set
            {
                this.MoneySavedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mood
        {
            get
            {
                return this.MoodField;
            }
            set
            {
                this.MoodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProgressRecordsHoangPxid
        {
            get
            {
                return this.ProgressRecordsHoangPxidField;
            }
            set
            {
                this.ProgressRecordsHoangPxidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RecordedAt
        {
            get
            {
                return this.RecordedAtField;
            }
            set
            {
                this.RecordedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.SupportMethodsHoangPx SupportMethod
        {
            get
            {
                return this.SupportMethodField;
            }
            set
            {
                this.SupportMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SupportMethodId
        {
            get
            {
                return this.SupportMethodIdField;
            }
            set
            {
                this.SupportMethodIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.SystemUserAccount User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAchievementNhuNq", Namespace="http://schemas.datacontract.org/2004/07/SmokeQuit.SoapApiServices.DuongLNT.SoapMo" +
        "dels")]
    public partial class UserAchievementNhuNq : object
    {
        
        private System.DateTime AchievedAtField;
        
        private LeaderboardsDuongLntWCFServiceRef.AchievementNhuNq AchievementField;
        
        private int AchievementIdField;
        
        private System.Nullable<int> CommentCountField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private System.Nullable<int> LikeCountField;
        
        private bool NotificationSentField;
        
        private System.Nullable<int> RewardPointsField;
        
        private bool SharedField;
        
        private LeaderboardsDuongLntWCFServiceRef.SystemUserAccount UserField;
        
        private int UserAchievementNhuNqidField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AchievedAt
        {
            get
            {
                return this.AchievedAtField;
            }
            set
            {
                this.AchievedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.AchievementNhuNq Achievement
        {
            get
            {
                return this.AchievementField;
            }
            set
            {
                this.AchievementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AchievementId
        {
            get
            {
                return this.AchievementIdField;
            }
            set
            {
                this.AchievementIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CommentCount
        {
            get
            {
                return this.CommentCountField;
            }
            set
            {
                this.CommentCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LikeCount
        {
            get
            {
                return this.LikeCountField;
            }
            set
            {
                this.LikeCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NotificationSent
        {
            get
            {
                return this.NotificationSentField;
            }
            set
            {
                this.NotificationSentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RewardPoints
        {
            get
            {
                return this.RewardPointsField;
            }
            set
            {
                this.RewardPointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Shared
        {
            get
            {
                return this.SharedField;
            }
            set
            {
                this.SharedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.SystemUserAccount User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserAchievementNhuNqid
        {
            get
            {
                return this.UserAchievementNhuNqidField;
            }
            set
            {
                this.UserAchievementNhuNqidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoachesLocDpx", Namespace="http://schemas.datacontract.org/2004/07/SmokeQuit.SoapApiServices.DuongLNT.SoapMo" +
        "dels")]
    public partial class CoachesLocDpx : object
    {
        
        private string BioField;
        
        private LeaderboardsDuongLntWCFServiceRef.ChatsLocDpx[] ChatsLocDpxesField;
        
        private int CoachesLocDpxidField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private string EmailField;
        
        private string FullNameField;
        
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bio
        {
            get
            {
                return this.BioField;
            }
            set
            {
                this.BioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.ChatsLocDpx[] ChatsLocDpxes
        {
            get
            {
                return this.ChatsLocDpxesField;
            }
            set
            {
                this.ChatsLocDpxesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoachesLocDpxid
        {
            get
            {
                return this.CoachesLocDpxidField;
            }
            set
            {
                this.CoachesLocDpxidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportMethodsHoangPx", Namespace="http://schemas.datacontract.org/2004/07/SmokeQuit.SoapApiServices.DuongLNT.SoapMo" +
        "dels")]
    public partial class SupportMethodsHoangPx : object
    {
        
        private string DescriptionField;
        
        private string MethodNameField;
        
        private LeaderboardsDuongLntWCFServiceRef.ProgressRecordsHoangPx[] ProgressRecordsHoangPxesField;
        
        private int SupportMethodsHoangPxidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName
        {
            get
            {
                return this.MethodNameField;
            }
            set
            {
                this.MethodNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.ProgressRecordsHoangPx[] ProgressRecordsHoangPxes
        {
            get
            {
                return this.ProgressRecordsHoangPxesField;
            }
            set
            {
                this.ProgressRecordsHoangPxesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupportMethodsHoangPxid
        {
            get
            {
                return this.SupportMethodsHoangPxidField;
            }
            set
            {
                this.SupportMethodsHoangPxidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AchievementNhuNq", Namespace="http://schemas.datacontract.org/2004/07/SmokeQuit.SoapApiServices.DuongLNT.SoapMo" +
        "dels")]
    public partial class AchievementNhuNq : object
    {
        
        private string AchievementNameField;
        
        private int AchievementNhuNqidField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private string CriteriaTypeField;
        
        private double CriteriaValueField;
        
        private string DescriptionField;
        
        private LeaderboardsDuongLntWCFServiceRef.UserAchievementNhuNq[] UserAchievementNhuNqsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AchievementName
        {
            get
            {
                return this.AchievementNameField;
            }
            set
            {
                this.AchievementNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AchievementNhuNqid
        {
            get
            {
                return this.AchievementNhuNqidField;
            }
            set
            {
                this.AchievementNhuNqidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CriteriaType
        {
            get
            {
                return this.CriteriaTypeField;
            }
            set
            {
                this.CriteriaTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CriteriaValue
        {
            get
            {
                return this.CriteriaValueField;
            }
            set
            {
                this.CriteriaValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LeaderboardsDuongLntWCFServiceRef.UserAchievementNhuNq[] UserAchievementNhuNqs
        {
            get
            {
                return this.UserAchievementNhuNqsField;
            }
            set
            {
                this.UserAchievementNhuNqsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeaderboardsDuongLntWCFServiceRef.ILeaderboardsDuongLntSoapService")]
    public interface ILeaderboardsDuongLntSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaderboardsDuongLntSoapService/GetLeaderboardsDuongLnt", ReplyAction="http://tempuri.org/ILeaderboardsDuongLntSoapService/GetLeaderboardsDuongLntRespon" +
            "se")]
        System.Threading.Tasks.Task<LeaderboardsDuongLntWCFServiceRef.LeaderboardsDuongLnt[]> GetLeaderboardsDuongLntAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaderboardsDuongLntSoapService/GetLeaderboardsDuongLntById", ReplyAction="http://tempuri.org/ILeaderboardsDuongLntSoapService/GetLeaderboardsDuongLntByIdRe" +
            "sponse")]
        System.Threading.Tasks.Task<LeaderboardsDuongLntWCFServiceRef.LeaderboardsDuongLnt> GetLeaderboardsDuongLntByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaderboardsDuongLntSoapService/Create", ReplyAction="http://tempuri.org/ILeaderboardsDuongLntSoapService/CreateResponse")]
        System.Threading.Tasks.Task<int> CreateAsync(LeaderboardsDuongLntWCFServiceRef.LeaderboardsDuongLnt leaderboards);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaderboardsDuongLntSoapService/Update", ReplyAction="http://tempuri.org/ILeaderboardsDuongLntSoapService/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(LeaderboardsDuongLntWCFServiceRef.LeaderboardsDuongLnt leaderboards);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaderboardsDuongLntSoapService/Delete", ReplyAction="http://tempuri.org/ILeaderboardsDuongLntSoapService/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ILeaderboardsDuongLntSoapServiceChannel : LeaderboardsDuongLntWCFServiceRef.ILeaderboardsDuongLntSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class LeaderboardsDuongLntSoapServiceClient : System.ServiceModel.ClientBase<LeaderboardsDuongLntWCFServiceRef.ILeaderboardsDuongLntSoapService>, LeaderboardsDuongLntWCFServiceRef.ILeaderboardsDuongLntSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LeaderboardsDuongLntSoapServiceClient() : 
                base(LeaderboardsDuongLntSoapServiceClient.GetDefaultBinding(), LeaderboardsDuongLntSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ILeaderboardsDuongLntSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeaderboardsDuongLntSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LeaderboardsDuongLntSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), LeaderboardsDuongLntSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeaderboardsDuongLntSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LeaderboardsDuongLntSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeaderboardsDuongLntSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LeaderboardsDuongLntSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeaderboardsDuongLntSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<LeaderboardsDuongLntWCFServiceRef.LeaderboardsDuongLnt[]> GetLeaderboardsDuongLntAsync()
        {
            return base.Channel.GetLeaderboardsDuongLntAsync();
        }
        
        public System.Threading.Tasks.Task<LeaderboardsDuongLntWCFServiceRef.LeaderboardsDuongLnt> GetLeaderboardsDuongLntByIdAsync(int id)
        {
            return base.Channel.GetLeaderboardsDuongLntByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> CreateAsync(LeaderboardsDuongLntWCFServiceRef.LeaderboardsDuongLnt leaderboards)
        {
            return base.Channel.CreateAsync(leaderboards);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(LeaderboardsDuongLntWCFServiceRef.LeaderboardsDuongLnt leaderboards)
        {
            return base.Channel.UpdateAsync(leaderboards);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILeaderboardsDuongLntSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILeaderboardsDuongLntSoapService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7115/LeaderboardsDuongLntSoapService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LeaderboardsDuongLntSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ILeaderboardsDuongLntSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LeaderboardsDuongLntSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ILeaderboardsDuongLntSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ILeaderboardsDuongLntSoapService,
        }
    }
}
